import { Injectable } from '@angular/core';
import { of, Observable } from 'rxjs';

interface Application {
  team: number;
  id: number;
  name: string;
  description: string;
  link: string;
  operation: string;
  domain: string;
  vendor: string;
  solution: string;
  business: string;
  is_active: number;
}

interface Team {
  team: number;
  id: number;
  name: string;
  email: string;
  team_boss: string;
}

interface Envanter {
  team: number;
  id: number;
  type: string;
  domain: string;
  environment: string;
  name: string;
  address: string;
}

interface MockData {
  [key: string]: Application[] | Team[]; // Uygulama ve ekip listesi için tip tanımı
}

@Injectable({
  providedIn: 'root',
})
export class MockDataService {
  private mockData: MockData = {
    uygulamalistesi: [
      {
        team: 1,
        id: 1,
        name: 'TTPORT',
        description: 'Kurum Intranet Portalı',
        link: 'https://ttport.turktelekom.com.tr/ ',
        operation: 'Gökhan Yıldız',
        domain: 'Sabit',
        vendor: 'Innova',
        solution: 'Alper Subaşı',
        business: 'Eser Değirmencioğlu',
        is_active: 1,
      },
      {
        team: 1,
        id: 2,
        name: 'PORTTAKAL',
        description: 'Bayi Intranet Portalı',
        link: 'https://porttakal.turktelekom.com.tr/ ',
        operation: 'Gökhan Yıldız',
        domain: 'Sabit',
        vendor: 'Innova',
        solution: 'Alper Subaşı',
        business: 'Simay Gezer',
        is_active: 1,
      },
      {
        team: 1,
        id: 3,
        name: 'EDITT',
        description:
          'Kurum içi ve dışı resmi yazışmaların yapıldığı doküman oluşturma ve takibinin yapıldığı uygulama',
        link: 'https://editt.turktelekom.com.tr',
        operation: 'Gökhan Akbulut',
        domain: 'Sabit',
        vendor: 'Innova',
        solution: 'Yasemin Ülküsayar Köken',
        business: 'Tüm telekom çalışanları',
        is_active: 1,
      },
      {
        team: 1,
        id: 4,
        name: 'EDITT Assistt',
        description:
          'Assitt tarafındaki Kurum içi ve dışı resmi yazışmaların yapıldığı doküman oluşturma ve takibinin yapıldığı uygulama',
        link: 'https://assistteditt.turktelekom.com.tr',
        operation: 'Gökhan Akbulut',
        domain: 'Sabit',
        vendor: 'Innova',
        solution: 'Yasemin Ülküsayar Köken',
        business: 'Tüm telekom çalışanları',
        is_active: 1,
      },
      {
        team: 1,
        id: 5,
        name: 'Kanal İletişim Platformu',
        description:
          'Satış ve Müşteri Hizmetleri Kanalları’nı bilgilendirmek amacıyla kullanılan Pusula ve Cankurtaran portallerinin yeni bir platformda tekilleştirilerek, tutarlı bir sistem üzerinde, kullanım kolaylığı sunan ve teknoloji olarak yenilenmiş, güncellemelere açık bir altyapı sağlanması hedeflenmektedir.',
        link: 'https://pusulayeni.turktelekom.com.tr',
        operation: 'Gökhan Yıldız',
        domain: 'Sabit',
        vendor: 'Innova',
        solution: 'Alper Subaşı',
        business: 'Arda Koç',
        is_active: 1,
      },
      {
        team: 1,
        id: 6,
        name: 'RSA Archer',
        description:
          'Kurumsan risk uygulaması - GRC uygulamasına geçicek. desteği yok',
        link: 'https://kry.turktelekom.com.tr/',
        operation: 'Sezgin Çalışkan',
        domain: 'Sabit',
        vendor: 'Cogris',
        solution: '',
        business: 'Grup Risk Yönetimi Başkan Yardımcılığı',
        is_active: 0,
      },
      {
        team: 1,
        id: 7,
        name: 'ARIS',
        description:
          'TT iç süreç çizim ve süreç yönetimi----Kurumsan mimari çizim uygulaması - Hopex e uygulamasına geçti. desteği yok',
        link: 'https://sysportal.turktelekom.com.tr/',
        operation: 'Sezgin Çalışkan',
        domain: 'Sabit',
        vendor: 'Consulta',
        solution: '',
        business: 'Mustafa Olcay Sakıcı',
        is_active: 0,
      },
      {
        team: 1,
        id: 8,
        name: 'EATYS',
        description: 'Erişim Altyapı Taşeron Yönetim Sistemi',
        link: 'http://key.turktelekom.com.tr/EATYS',
        operation: 'Özge Kata',
        domain: 'Sabit',
        vendor: 'Innova',
        solution: 'Umut Demirtaş',
        business: 'Kontrat Yönetimi Müdürlüğü',
        is_active: 1,
      },
      {
        team: 1,
        id: 9,
        name: 'Filoportal',
        description: 'Filo takip ve Nakliye yönetim sistemi',
        link: 'https://filoportal.turktelekom.com.tr/',
        operation: 'Sezgin Çalışkan',
        domain: 'Sabit',
        vendor: 'Innova',
        solution: '',
        business: '',
        is_active: 1,
      },
      {
        team: 1,
        id: 10,
        name: 'Elektrik Portal',
        description: 'TT Elektrik Abonelik Bilgileri Takip Portali ',
        link: 'https://elektrikportal.turktelekom.com.tr',
        operation: 'Ömer Faruk Tokel',
        domain: 'Sabit',
        vendor: 'Technix',
        solution: '',
        business: '',
        is_active: 0,
      },
      {
        team: 1,
        id: 11,
        name: 'HPTS',
        description:
          'Inhouse, outsource çalışan bilgilerinin düzenli olarak BTK ya raporlanmasını sağlayan araç',
        link: 'https://hpts.turktelekom.com.tr',
        operation: 'Özge Kata',
        domain: 'Sabit',
        vendor: 'Inhouse',
        solution: 'Oğuzhan Sazak',
        business: 'İK Ortak Servisler ve Raporlama',
        is_active: 1,
      },
      {
        team: 1,
        id: 12,
        name: 'HETTS',
        description: 'Taşeron Personel Hakediş Sistemi',
        link: 'https://hetts.turktelekom.com.tr',
        operation: 'Ömer Faruk Tokel',
        domain: 'Sabit',
        vendor: 'Uyumsoft',
        solution: 'Umut Taşdemir',
        business: 'Mustafa Terzi',
        is_active: 1,
      },
      {
        team: 1,
        id: 13,
        name: 'KVKK',
        description:
          'Kişisel verileri koruma kanunu kapsamında kullanıcı verilerini düzenleme uygulaması.',
        link: '',
        operation: 'Gökhan Yıldız',
        domain: 'Sabit',
        vendor: '',
        solution: '',
        business: '',
        is_active: 1,
      },
      {
        team: 1,
        id: 14,
        name: 'LSTS',
        description: 'TT Akademi LCD ekranların yönetimi',
        link: '',
        operation: 'Yusuf Elmasoğlu',
        domain: 'Sabit',
        vendor: 'Innova',
        solution: 'Ayşe TÜZÜN',
        business: 'Emre Gölçek',
        is_active: 0,
      },
      {
        team: 1,
        id: 15,
        name: 'OrgPublisher',
        description: 'Organizasyon Şeması Yazılımı',
        link: 'http://lexus01.msy.turktelekom.intra/PERS_PB/Chart/LoadChart/PERS_PB ',
        operation: 'Yıldız Köşker',
        domain: 'Sabit',
        vendor: 'Patika',
        solution: 'Ayşe Tüzün',
        business: 'Gizem Yahşi',
        is_active: 1,
      },
      {
        team: 1,
        id: 16,
        name: 'OTMS',
        description:
          'Çalışanlara özel günlerde gönderilen otomatik mail gönderim uygulaması',
        link: '',
        operation: 'Yıldız Köşker',
        domain: 'Sabit',
        vendor: 'Inhouse',
        solution: '',
        business: '',
        is_active: 0,
      },
      {
        team: 1,
        id: 17,
        name: 'ProjeTTT',
        description: 'Geliştirme taleplerinin toplandığı uygulama',
        link: 'https://projettt.turktelekom.com.tr/',
        operation: 'Yıldız Köşker',
        domain: 'Sabit',
        vendor: 'Innova',
        solution: 'Emrullah Durmaz',
        business: '',
        is_active: 1,
      },
      {
        team: 1,
        id: 18,
        name: 'PTS',
        description: 'Pazar Takip Uygulaması',
        link: 'https://pazartakip.turktelekom.com.tr/',
        operation: 'Ömer Faruk Tokel',
        domain: 'Sabit',
        vendor: 'Innova',
        solution: 'Yasemin Ülküsayar Köken',
        business: 'Cengizhan Gergef',
        is_active: 1,
      },
      {
        team: 1,
        id: 19,
        name: 'TT Akademi',
        description: 'Türk Telekom eğitim platformu portalı',
        link: 'https://ttakademi.turktelekom.com.tr',
        operation: 'Özge Kata',
        domain: 'Sabit',
        vendor: 'Innova',
        solution: 'Ayşe Tüzün',
        business: 'Emre Gölçek',
        is_active: 1,
      },
      {
        team: 1,
        id: 20,
        name: 'TT Core',
        description:
          'SAP,LDAP ve SMS entegrasyonunu sağlayan webservis uygulaması',
        link: 'https://ttport.turktelekom.com.tr/ ',
        operation: 'Ömer Faruk Tokel',
        domain: 'Sabit',
        vendor: 'Inhouse',
        solution: '',
        business: '',
        is_active: 1,
      },
      {
        team: 1,
        id: 21,
        name: 'TT Seyahat',
        description:
          'Türk Telekom Grubu çalışanlarının yurtiçi ulaşım (uçak) ve konaklama alımlarını yönetebilecekleri bir web ara yüzüdür. ',
        link: 'https://ttseyahat.turktelekom.com.tr/',
        operation: 'Sezgin Çalışkan',
        domain: 'Sabit',
        vendor: 'ERS',
        solution: '',
        business: '',
        is_active: 0,
      },
      {
        team: 1,
        id: 22,
        name: 'Seyahat Portal',
        description:
          'Türk Telekom Grubu çalışanlarının yurtiçi ulaşım (uçak) ve konaklama alımlarını yönetebilecekleri bir web ara yüzüdür. ',
        link: 'https://ttseyahatportal.turktelekom.com.tr/',
        operation: 'Sezgin Çalışkan',
        domain: 'Sabit',
        vendor: 'ERS',
        solution: 'Yasemin Ülküsayar Köken',
        business: 'Tüm telekom çalışanları',
        is_active: 1,
      },
      {
        team: 1,
        id: 23,
        name: 'UPYS',
        description: 'İK nın kullandığı ücret ve prim yönetimi sistemi',
        link: 'https://upys6.turktelekom.com.tr/',
        operation: 'Özge Kata',
        domain: 'Sabit',
        vendor: 'Inhouse',
        solution: 'Yasemin Ülküsayar Köken',
        business: 'Ücret Prim ekibi',
        is_active: 1,
      },
      {
        team: 1,
        id: 24,
        name: 'Vitta',
        description:
          'Satış ve Müşteri Hizmetleri Kanalları’nı bilgilendirmek amacıyla kullanılan Pusula ve Cankurtaran portallerinin yeni bir platformda tekilleştirilerek, tutarlı bir sistem üzerinde, kullanım kolaylığı sunan ve teknoloji olarak yenilenmiş, güncellemelere açık bir altyapı sağlanması hedeflenmektedir.',
        link: 'https://pusulayeni.turktelekom.com.tr',
        operation: 'Gökhan Yıldız',
        domain: 'Sabit',
        vendor: 'Innova',
        solution: 'Alper Subaşı',
        business: 'Arda Koç',
        is_active: 0,
      },
      {
        team: 1,
        id: 25,
        name: 'Artifactory',
        description:
          'Deployment dosyalarının depolandığı araç, operasyon deployment dosyalarını buradan almaktadır',
        link: 'https://ttartifactory.turktelekom.com.tr/artifactory/webapp/#/home',
        operation: 'Yıldız Köşker',
        domain: 'Sabit',
        vendor: '',
        solution: 'Emrullah Durmaz',
        business: 'Banu Turgut Kuseyiroğlu',
        is_active: 1,
      },
      {
        team: 1,
        id: 26,
        name: 'CC Akademi',
        description: 'Müşteri hizmetleri eğitim platformu',
        link: 'https://ccakademi.turktelekom.com.tr',
        operation: 'Özge Kata',
        domain: 'Mobil',
        vendor: 'Enocta',
        solution: 'İnci Yalçınkaya',
        business: 'Mustafa Olcay Sakıcı',
        is_active: 1,
      },
      {
        team: 1,
        id: 27,
        name: 'İş Akış Portalı',
        description:
          'Oracle BPM iş süreçleri yönetim uygulaması. TTG iç süreçleri yönetim ve takibi IAP üzerinde yapılmaktadır',
        link: 'https://iap/',
        operation: 'Yusuf Elmasoğlu',
        domain: 'Mobil',
        vendor: 'Innova',
        solution: 'Yasemin Ülküsayar Köken',
        business: '',
        is_active: 1,
      },
      {
        team: 1,
        id: 28,
        name: 'Jenkins',
        description:
          'Açık kaynak kodlu bir otomasyon sunucusudur.Jenkins yazılım geliştirme sürecinin parçalarını otomatikleştirmeye yardımcı oluyor.',
        link: '',
        operation: 'Yıldız Köşker',
        domain: 'Mobil',
        vendor: '',
        solution: 'Emrullah Durmaz',
        business: 'Banu Turgut Kuseyiroğlu',
        is_active: 0,
      },
      {
        team: 1,
        id: 29,
        name: 'KGO',
        description: 'Bayi Eğitim Portali',
        link: 'https://kgo.turktelekom.com.tr',
        operation: 'Özge Kata',
        domain: 'Mobil',
        vendor: 'Enocta',
        solution: '',
        business: '',
        is_active: 1,
      },
      {
        team: 1,
        id: 30,
        name: 'Video Portal',
        description:
          'TTAkademi, TTPort gibi iç ve dış uygulamalarda videoların stream edilmesini sağlayan CDN aracı',
        link: 'https://videocdnvodpanel.turktelekom.com.tr',
        operation: 'Gökhan Yıldız',
        domain: 'Sabit',
        vendor: 'Medianova',
        solution: 'Ayşe Tüzün',
        business: '',
        is_active: 1,
      },
      {
        team: 1,
        id: 31,
        name: 'Hazine Portal',
        description:
          'Hazine Operasyonları işlemlerinin tamamının uçtan uca gerçekleştirildiği, anlık raporlamaların ve görüntülemelerin yapılabildiği, mobil imza ile talimatların imzalanıp bankalara iletildiği, gün sonunda ekstre mutabakatının yapılabildiği uygulamadır.',
        link: 'https://hazineportal.turktelekom.com.tr',
        operation: 'Sezgin Çalışkan',
        domain: 'Sabit',
        vendor: 'Innova',
        solution: '',
        business: '',
        is_active: 1,
      },
      {
        team: 1,
        id: 32,
        name: 'Araç Takip Sistemi',
        description:
          'Şirket araçlarına takılı GPS cihazları ile anlık takibi, raporlaması ve periyodik kontrollerinin yapıldığı uygulamadır.',
        link: '',
        operation: 'Ömer Faruk Tokel',
        domain: 'Sabit',
        vendor: 'Mobiliz',
        solution: '',
        business: '',
        is_active: 1,
      },
      {
        team: 1,
        id: 33,
        name: 'Megahopex',
        description:
          'Kurumsal Mimari Modelleme uygulaması olarak kullanılmaktadır. Uygulama, service, fonksiyonalite bilgilerini ve uygulamalar arasındaki detayların raporlanmasını ve olası güncellemelerdeki impact analizlerini sağlamaktadır.',
        link: '',
        operation: 'Ömer Faruk Tokel',
        domain: 'Sabit',
        vendor: 'Proya',
        solution: '',
        business: '',
        is_active: 1,
      },
      {
        team: 1,
        id: 34,
        name: 'Mucit',
        description:
          'Türk Telekom çalışanlarının yenilikçi ve yaratıcı fikirlerinin toplandığı ve değerlendirildiği bir online platformdur.',
        link: 'https://mucit.turktelekom.com.tr',
        operation: 'Gökhan Yıldız',
        domain: 'Sabit',
        vendor: 'Innova',
        solution: 'Alper Subaşı',
        business: '',
        is_active: 1,
      },
      {
        team: 1,
        id: 35,
        name: 'İşe Alım Uygulaması',
        description:
          'Türk Telekom personel alımı kapsamında, talepten başlayıp işe alım ile sonlanan sürecin uçtan uca otomasyon üzerinden yürütülmesi hedeflenmektedir.',
        link: 'https://basvuru.turktelekomkariyer.com.tr/',
        operation: 'Yusuf Elmasoğlu',
        domain: 'Sabit',
        vendor: 'HRPeak',
        solution: 'Ayşe Tüzün',
        business: '',
        is_active: 1,
      },
      {
        team: 1,
        id: 36,
        name: 'SSMS',
        description: 'Simkart ve bakiye kart sipariş ve üretim takip sistemi',
        link: 'https://ssms.turktelekom.com.tr:8443/SSMS/ ',
        operation: 'Sezgin Çalışkan',
        domain: 'Mobil',
        vendor: 'Innova',
        solution: 'Ayşe Tüzün',
        business: 'Emrah Apaydın',
        is_active: 1,
      },
      {
        team: 1,
        id: 37,
        name: 'EASYS',
        description: 'Erişim Altyapı Sipariş Yönetim Sistemi',
        link: 'http://key.turktelekom.com.tr/EATYS',
        operation: 'Özge Kata',
        domain: 'Sabit',
        vendor: 'Innova',
        solution: 'Umut Demirtaş',
        business: 'Kontrat Yönetimi Müdürlüğü',
        is_active: 1,
      },
      {
        team: 1,
        id: 38,
        name: 'Sözleşme Yönetim Sistemi',
        description:
          'Türk Telekomünikasyon AŞ, TT Mobil İletişim Hizmetleri AŞ ve TTnet AŞ) kullanılan farklı sözleşme modüllerini tek çatı altında toplayarak süreç yönetiminin uçtan uca takibini sağlamak.',
        link: 'https://ttsys.turktelekom.com.tr',
        operation: 'Yıldız Köşker',
        domain: 'Sabit',
        vendor: 'Microdestek',
        solution: 'Ayşe Tüzün',
        business: '',
        is_active: 1,
      },

      {
        team: 1,
        id: 39,
        name: 'Ziyaretçi Takip Sistemi (ZTS)',
        description:
          'Türk Telekom binalarına ziyaretçi olarak gelen kişilerin rezervasyon, kayıt ve raporlama süreçlerinin yürütüldüğü uygulamadır. ',
        link: 'https://zts.turktelekom.com.tr/',
        operation: 'Yıldız Köşker',
        domain: 'Sabit',
        vendor: 'Argenova',
        solution: 'Salih Zeki Akkaya',
        business: 'Filiz Bayraktar',
        is_active: 1,
      },
      {
        team: 1,
        id: 40,
        name: 'Araç Takip Sistemi',
        description:
          'Şirket araçlarının üzerlerine takılı GPS cihazları ile anlık takibi, raporlaması ve periyodik kontrollerinin yapıldığı uygulamadır.',
        link: 'https://aractakip.turktelekom.com.tr',
        operation: 'Ömer Faruk Tokel',
        domain: 'Sabit',
        vendor: 'Mobiliz',
        solution: 'Umut Demirtaş',
        business: 'Sezin Güner Örün',
        is_active: 1,
      },
      {
        team: 1,
        id: 41,
        name: 'Hasar Takip Sistemi',
        description:
          'TT, TT Mobil ve TTNET’in Tüm Riskler poliçelerine ait hasarlar, İş Veren Sorumluluk Poliçelerine ait İş Kazası vb. hasarlar ile Sorumluluk Poliçelerine konu olan 3.Şahıs’lara verilen hasarların süreçleri bu sistem üzerinde işletilecektir. ',
        link: 'https://iap/hasartakip/login',
        operation: 'Yusuf Elmasoğlu',
        domain: 'Mobil',
        vendor: '',
        solution: 'Yasemin Ülküsayar Köken',
        business: '',
        is_active: 1,
      },
      {
        team: 1,
        id: 42,
        name: 'DKYS',
        description: 'Dışkaynak Yönetimi için kullanılmaktadır. ',
        link: 'https://ispaydasim.turktelekom.com.tr',
        operation: 'Sezgin Çalışkan',
        domain: 'Sabit',
        vendor: 'MicroDestek',
        solution: 'Ayşe Tüzün',
        business: 'Dış Kaynak Birimi',
        is_active: 1,
      },
      {
        team: 1,
        id: 43,
        name: 'İAP Arabağlantı',
        description:
          'TT grup şirketleri ile İşletmeci şebekesi arasında tesis edilecek arabağlantı ve ilgili diğer hizmetlere ilişkin süreçlerin sistem üzerinden yürütülmesi, takibi ve raporlaması için kullanılmaktadır',
        link: 'https://isakisportal.turktelekom.com.tr/ng-interconnection/',
        operation: 'Yusuf Elmasoğlu',
        domain: 'Mobil',
        vendor: 'MSU',
        solution: '',
        business: '',
        is_active: 1,
      },
      {
        team: 1,
        id: 44,
        name: 'Mobil Market',
        description: 'TT Mobil Market',
        link: 'https://ttmobilmarket.turktelekom.com.tr/TTMarket/login',
        operation: 'Özge Kata',
        domain: 'Mobil',
        vendor: 'Inhouse',
        solution: 'Hazal Şimşir Ayhan',
        business: '',
        is_active: 1,
      },
      {
        team: 1,
        id: 45,
        name: 'Akıllı Çağrı',
        description: 'Akıllı Çağrı',
        link: 'https://mobiluygulama.turktelekom.com.tr/',
        operation: 'Özge Kata',
        domain: 'Mobil',
        vendor: 'Inhouse',
        solution: 'Hazal Şimşir Ayhan',
        business: '',
        is_active: 1,
      },
      {
        team: 1,
        id: 46,
        name: 'Kodeks',
        description: 'Bilgi Bankası',
        link: 'https://kodeks.turktelekom.com.tr/login ',
        operation: 'Gökhan Akbulut',
        domain: 'Sabit',
        vendor: 'Inhouse',
        solution: 'Kübra Kırtekin',
        business: 'TT Çalışanları',
        is_active: 1,
      },
      {
        team: 1,
        id: 47,
        name: 'DDKINTRA',
        description: 'Turktelekom iç müşterilerine sunulan bulut hizmeti.',
        link: 'https://dijitaldepokurumsalintra.turktelekom.com.tr',
        operation: 'Gökhan Akbulut',
        domain: 'Sabit',
        vendor: 'Divvydrive',
        solution: 'Kübra Kırtekin',
        business: 'TT Çalışanları',
        is_active: 1,
      },
      {
        team: 1,
        id: 48,
        name: 'KurTT',
        description:
          'Kurumsal Risk, İç Kontrol, İş Sürekliliği ve İç Denetim ile birlikte Regülasyon UyumDirektörlüğü faaliyetlerinin şirketin tüm iş birimlerini de içine alacak şekilde yürütülmesi amacıyla kullanılan web uygulamasıdır. ',
        link: 'https://kurtt.turktelekom.com.tr',
        operation: 'Gökhan Akbulut',
        domain: 'Sabit',
        vendor: '',
        solution: '',
        business: '',
        is_active: 1,
      },
    ],

    ekipler: [
      {
        team: 1,
        id: 1,
        name: 'Kurumsal Uygulama Operasyonları',
        email: 'test@turktelekom.com.tr',
        team_boss: 'Onur Abi',
      },
      {
        team: 2,
        id: 2,
        name: 'Middleware Ekibi',
        email: 'test2@turktelekom.com.tr',
        team_boss: 'Onur Abi',
      },
      {
        team: 3,
        id: 3,
        name: 'Sabit Dizin Ekibi',
        email: 'test3@turktelekom.com.tr',
        team_boss: 'Onur Abi',
      },
    ],
  };

  getData(endpoint: string): Observable<any> {
    return of(this.mockData[endpoint]);
  }
}
